# Made up config for logstash
exclude_hosts: ["ignore-me"]
defaults:
    command: logbin/log.sh
    envars:
        LOGSTASH_PUBLIC_HOST: myhost.example.com
              
hosts:
    - name: "postgres*"
      envars:
        LOGSTASH_TYPE: postgres
        LOGSTASH_TAGS: "[postgres]"
      filter_lines:
        - "connection received"
        - "connection authorized"
        - "disconnection:"

    - name: "*"
      envars:
        LOGSTASH_TYPE: test

